blank_issues_enabled: false
contact_links:
  - name: VelociRust community on Discord
    url: 
    about: Please ask and answer questions here.
  - name: VelociRust community on Matrix
    url: 
    about: Please ask and answer questions here.
  - name: VelociRust documentation
    url: 
    about: Documentation for VelociRust
